# Generated by Django 5.0.6 on 2024-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='no bio avaiable'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_info',
            field=models.CharField(blank=True, default='No contact info available', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='no phone number available', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAngMBIgACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAAAwUBBAYCB//EADkQAAICAAIGBwcDAgcAAAAAAAABAgMEEQUSITFBURMiMmFxweEjUoGRobHRM0LwFHIGJTRDYoKS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwD7iAAAAAABvIACJ3JvKEXN9275nmTmlnOca13flgTgr543Bwz18S5PkpN/Yiek8AuFj+DAtRmVUdJYDPfZHvyZsVYnDW7KsXk+Tf5A3QRJ2R3pTXNbGeo2xk8t0uT2AewAAAAAAAAAAAI7J5JZLOT3IDNk1Bbdre5LiQ3TjCDsxU1GC4cPUjxeJhgq9e161st0c/5sOexWJtxNmvbJvkuCAsMVpmT6mEhqx96S2/BFbbdZdLWtnKb72RgqAAAAADYoxmIw/wCla0vde1FrhdLU35QxUVCXCXD0KIAdcnOCzz16+fFfkljJSipReaZzWj9I2YRqEutTxjxXgXtc4ygrsO1KEtrS/m8itkGIyUopramZAAAAAAMTajFtvJI1MRfHDUzxF2/hH7Imn17FHhHa/I5/S2K/qMU4xfs69ke/mwNbEXTxFsrLXnJ/QiAKgAAAMjw2+AGAAAAAA3dGY6WEtyk86pdpcu80gB1sXqTUovOuf0fqTlNoTE9LVLC2ftXV8C1pk3HKW+LyZFSAAAYbMkd79lLhnsA08bf0GBstzynZ2fju+hze5ZFx/iCzJ00rYktbL6LzKcoAAIHquErJqEIuUnuSPJcaKo1KelkutPd4BWcNo6utKV2Vk/obkUo9lJeGwyAPE64WLKyKknwaK7GaO1YueHTaW+H4LQAcyDd0pQqrlOKyjPblyZpBAAAS4a54fEQtX7Xm/DidSmuljOPZsjvOROj0fZ0mjqpb3W0vls+xFWICAAju26i5zX5JCO7fX/f5Ac/pyTlj2n+2KXmV5v6aX+Yz/tX2NAoAAIHR1JRqhFblFHOHQYSfS4euXHVSfjxCpgAAAAGjpZJ4VPipopy20xZlVGvi5Z/AqQgAABd6Fk3o/ER5SbXyKQutB/6PE+PkRVzHakzJiPZXgZAEV/YT5ST+pKeLYucJRzyzWQFDp+GrjIz4SgvP0KwvNNwduDquS2wfWXLP1KMoAAIG9o3FKmbrm/Zy3N8GaIA6YFHhsddQtVPXh7r/ACbkdK1ZLXrmvDJhVgeLbI1Qc7HlFGhZpWOXs6W3/wA2aF+IsxEk7JZ5bktyAzir3iLpTe7guSIQAgAABfaIhqaLsb/fJ/govBZvkdRRV0WHw9HFJN/Db9yK2luMgAAABrzrjZG2iXZmm18fU5a2uVNkq5rKUXkzrbYvJTW2Udq7+4qtM4TpYLF0pPJdfvXMCkABUCajDW3v2cG1z4G5gdHqaVl66u+MOZaxSislsS3JcCKrK9Evfbbk+UUTLReHW92fM3QBoS0VQ+zKafjma9uirI7apqS5S2MtwBzU4Trlq2RcZcmeTpLqa7oONsU1370UuNwc8NJPbKEuywNUA9RjKclGKzbeSSKjc0Rhv6jFptdSvKUvI6GvrWSnwXVXn/O41sHh/wCjw0ao/qz3vv8AQ3IRUYKK4IivQAAAAAQyyqk817OW/u9CYw1mBz2lNHPDt3UrOl717voR6Lwytm7bEnCD2Lmy/adSaa1quXu+hGsNCFaWH7G9JAed62gbt+wAAAAAAA82QjODhNZxa2nozFOT6qzA53E0Om517Xt6vei40bgFhY9Pf+plsXu+puOmqE422R1rFsjz+BLCEpS17Mtm5cgFUXnrz7T+iJQAAAAAAAAABE62nrVvVfFcGSgCCUl/vQ1e/evmY6JPbCSaNgidMM81HJ847AInXNcPkedWXJ/In6Oa3WS/7JMzq2+/D/z6gQaknwfyMqqb4ZIm1bXvnH4R9THRSfasm+5PL7AeNSENtk14HpSlLZVHVXvSXke4Vwg84xyb3s9gRwrUXm+tLjJkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/2Q==', upload_to='profile_pics/'),
        ),
    ]
