# Generated by Django 5.0.6 on 2024-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_post_media_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='medias/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
