# Generated by Django 5.0.6 on 2024-11-12 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notifications_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like')], default='follow', max_length=10),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
